#ifndef REMOTE_DRIVE_CONFIG_H
#define REMOTE_DRIVE_CONFIG_H

#define IBUS_DIAGNOSTIC_ONLY             0
#define REMOTE_DRIVE_ENABLE              1
#define REMOTE_DRIVE_BENCH_TEST_ENABLE   1

#define REMOTE_M3508_RPM_LOW             160.0f
#define REMOTE_M3508_RPM_MID             320.0f
#define REMOTE_FULL_THROTTLE_BASE_SPEED  460.0f
#define REMOTE_FULL_THROTTLE_SCALE       (1600.0f / 460.0f)
#define REMOTE_FULL_THROTTLE_MAX_SPEED   (REMOTE_FULL_THROTTLE_BASE_SPEED * REMOTE_FULL_THROTTLE_SCALE)
#define REMOTE_M3508_RPM_HIGH            REMOTE_FULL_THROTTLE_MAX_SPEED

#define REMOTE_STICK_DEADZONE            0.05f
#define REMOTE_STICK_EXPO                1.00f

#endif
